# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

R: Sim

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [5]:
#Recuperando o exercicio 9 
genes = ["apoe", "myd88", "nfkb1", "isg15", "p53"]
apoe = [
    len(genes[0]),
    genes[0][:2],
    genes[0].count("a"),
    "hu" in genes[0]
]
print(apoe)

myd88=[
    len(genes[1]),
    genes[1][:2],
    genes[1].count("a"),
    "hu" in genes[1]
]
print(myd88)

nfkb1=[
    len(genes[2]),
    genes[2][:2],
    genes[2].count("a"),
    "hu" in genes[2]
]
print(nfkb1)

isg15=[
    len(genes[3]), 
    genes[3][:2],
    genes[3].count("a"),
    "hu" in genes[3]
]
print(isg15)

p53=[
    len(genes[4]),
    genes[4][:2],
    genes[4].count("a"),
    "hu" in genes[4]
]
print(p53)

#MATRIZ 
matriz_genes = [apoe, myd88, nfkb1, isg15, p53]
print(matriz_genes)

[4, 'ap', 1, False]
[5, 'my', 0, False]
[5, 'nf', 0, False]
[5, 'is', 0, False]
[3, 'p5', 0, False]
[[4, 'ap', 1, False], [5, 'my', 0, False], [5, 'nf', 0, False], [5, 'is', 0, False], [3, 'p5', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [ ]:
#Recuperando o exercicio 2
matriz_genes = [apoe, myd88, nfkb1, isg15, p53]
print(matriz_genes)

import numpy 
matriz_genes_array = numpy.array(matriz_genes)
print(matriz_genes_array)

[[4, 'ap', 1, False], [5, 'my', 0, False], [5, 'nf', 0, False], [5, 'is', 0, False], [3, 'p5', 0, False]]
[['4' 'ap' '1' 'False']
 ['5' 'my' '0' 'False']
 ['5' 'nf' '0' 'False']
 ['5' 'is' '0' 'False']
 ['3' 'p5' '0' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [10]:
nfkb1 = matriz_genes_array[2]
nfkb1

array(['5', 'nf', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [14]:
verificacao_hu_todos = "hu" in genes[:]
verificacao_hu_todos

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [ ]:
print(genes[1][:2])
print(genes[1].count("a"))
print(genes[3][:2])
print(genes[3].count("a"))

my
0
is
0

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [20]:
#Recuperando exercicio 10:
genes = ["apoe", "myd88", "nfkb1", "isg15", "p53"]
dici_genes = {
    genes[0]: apoe,
    genes[1]:myd88,
    genes[2]: nfkb1,
    genes[3]: isg15,
    genes[4]: p53
}
dici_genes

#Executando exercicio 7:
import pandas
df_dici_genes = pandas.DataFrame(dici_genes)
print(df_dici_genes)

    apoe  myd88  nfkb1  isg15    p53
0      4      5      5      5      3
1     ap     my     nf     is     p5
2      1      0      0      0      0
3  False  False  False  False  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [31]:
df_dici_genes.loc[[0,2]]

  apoe myd88 nfkb1 isg15 p53
0    4     5     5     5   3
2    1     0     0     0   0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [33]:
df_dici_genes.loc[3, ["apoe", "nfkb1"]]

apoe     False
nfkb1    False
Name: 3, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [ ]:
#Importando os dados
import pandas as pd  #carregando pacote
import os   
os.listdir()   #acessando local
DataFrame = pd.read_csv('data_6.csv')  #importando dados
DataFrame.head()   #visualização 5 primeiros

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [ ]:
#Dicionário DataFrame - dados
#Número de entradas
num_entradas = DataFrame.shape[0]   #.shape (tamanho)
print(num_entradas)
#Lista com classe das colunas
classes_colunas = list(DataFrame.dtypes)    #.dtypes (tipos)
print(classes_colunas)
#Elementos de cada classe
contagem_classes = DataFrame.dtypes.value_counts().to_dict()   #.value_counts (valores contados)
print(contagem_classes)
#Lista
colunas = [DataFrame.iloc[:,0], DataFrame.iloc[:,3], DataFrame.iloc[:, 8]]   #.iloc (localização - 1)
print(colunas)
médias = []
desvios = []
terceiro_quartil = []
#Calculando valores
for col in colunas:
    médias.append(col.mean())  #.append (adicionar) + col.mean (valor da média)
    desvios.append(col.std())  #.append (adicionar) + col.std (valor do desvio padrão)
    terceiro_quartil.append(col.quantile(0.75))  #.append (adicionar) + col.quantile (valor do quatil definido por qual parte ele vai ser 0.75, 0.25...)

36634
[dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64')]
{dtype('float64'): 11, dtype('O'): 4, dtype('int64'): 3}
[0        119736
1        448094
2        206893
3        333743
4        172534
          ...
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64, 0         498960.0
1        1322376.3
2         190724.4
3              0.0
4              0.0
           ...
36629          0.0
36630    1297057.5
36631     173286.9
36632    1499781.6
36633     373488.3
Name: eq_site_limit, Length: 36634, dtype: float64, 0         792148.90
1        1438163.57
2         192476.78
3          86854.48
4         246144.49
            ...
36629     155065.65
36630    1577500.79
36631     205527.97
36632    1768782.43
36633     596003.67
Name: tiv_2012, Length: 36634, dtype: float64]

In [ ]:
#Dicionário 
resultado_dicionario = {
    'num_entradas': num_entradas,  #difinição das chaves e seu valor atribuido
    'classes_colunas': classes_colunas, 
    'contagem_classes': contagem_classes, 
    'médias': médias, 
    'desvios': desvios,
    'terceiro_quartil': terceiro_quartil
}
print(resultado_dicionario)

{'num_entradas': 36634, 'classes_colunas': [dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64')], 'contagem_classes': {dtype('float64'): 11, dtype('O'): 4, dtype('int64'): 3}, 'médias': [np.float64(548661.9371894961), np.float64(731478.0068460993), np.float64(2571004.0973420865)], 'desvios': [np.float64(259912.9264939009), np.float64(17523003.588415086), np.float64(20367766.569178067)], 'terceiro_quartil': [np.float64(774252.0), np.float64(0.0), np.float64(1128871.1824999999)]}